### ISSUE TITLE
Is `ci.vanityfair.com` dir packed on a purpose?

### ISSUE THREAD

**Issue by ChALkeR** [guyellis/multi-level-cache#20]
_Disclaimer: I do not use the package, this was found during automated npm packages downloading._

Your current package size is 47 MiB packed, **250 MiB unpacked**. 250 MiB of that are inside the `ci.vanityfair.com` dir. I suspect that this probably got packed to the release by mistake.

If you don't want to pack that directory, add it to the `.gitignore` and/or `.npmingore`.

**Comment by guyellis** [comment]
Thanks @ChALkeR - I've published 0.0.14 - you are correct - that was unintentional.
