### ISSUE TITLE
Keys with unexpected lack of TTLs in Redis adapter

### ISSUE THREAD

**Issue by brokentone** [guyellis/multi-level-cache#41]
In the following code block, we see a key/value set in redis, followed by a TTL creation async:

https://github.com/guyellis/multi-level-cache/blob/e6625d9fd46c5c615944afe398468a528083e5fa/lib/cache-lib/redis.js#L29-L38

This CPS-format callback between the first request (creation of key/value) and the corresponding allocation of expiration creates a moment of varied length depending on external factors in which a key/value could be stored with no TTL. This would mean something with an anticipated low TTL could persist until forcibly evicted. Dealing with networked services and several points of failure (node app-side, redis server-side, or transit), the seems particularly undesirable, and in fact, relatively easy to mitigate.

There are at least 2 ways we could simply solve this:

### Option 1
Here we are able to see that we can append to the `set` command arbitrary additional redis commands: https://github.com/NodeRedis/node_redis#redis-commands
At least that is what I think we're looking at... somewhat less than obvious to me.

### Option 2
Multi can help us here, chaining several commands into a single "transaction" This also simplifies the code quite a bit...
https://github.com/NodeRedis/node_redis#clientmulticommands
It would seem the highlighted code block from above might become:
```
const transaction = client.set(key, JSON.stringify(value));
if (ttl > 0) {
  transaction.expire(key, ttl);
}
transaction.exec(callback);
```

With positive feedback on either approach, a PR will be immanent.

**Comment by guyellis** [comment]
Thanks @brokentone - I like both solutions you've suggested. I guess that I prefer the first solution as it semantically maps directly to what we want to do.

So I'm thinking that the highlighted code might become:

```js
var val = JSON.stringify(value);
if(ttl > 0) {
  client.set(key, val, 'EX', ttl, callback);
} else {
  client.set(key, val, callback);
}
```

What do you think?

**Comment by guyellis** [comment]
Fix has been merged to master - thanks @brokentone
