### ISSUE TITLE
No way to recover from errorState issues (resilience)

### ISSUE THREAD

**Issue by giles-v** [guyellis/multi-level-cache#94]
Putting this out there for feedback, and happy to submit a PR:

Right now, if a connection to Redis fails (e.g. emits `CONNECTION_BROKEN` from `node-redis` - see [the changelog](https://github.com/NodeRedis/node_redis/blob/master/changelog.md#breaking-changes), searching for the above string) then the Redis client enters a broken state, and needs to be re-created to continue.

Suppose we have an app server which has a decent uptime (weeks). That uses a Redis server, which suddenly goes offline for an hour. The connection enters a broken state, and even when the server comes back up, the connection is still in a broken state.

We could mitigate this by saving an error state in the client calling code (if a critical error is thrown - i.e. not `keyNotFound`), and then if we've gotten that, after a specific interval (30s) we try to recreate the instance of `multi-level-cache`. However, there's no way from the instance of MultiLevelCache to know that anything's wrong, because `errorState` is an internal property and not exported anywhere.

Would it make sense to export the `errorState`, so that we can create the instance of `multi-level-cache` as a singleton, and monitor that for errors and try to reconnect if relevant?

**Comment by guyellis** [comment]
@giles-v that sounds like a reasonable approach. Feel free to submit a PR based on that idea or something else if it morphs while you're writing it and I'll try and work with you to get that into the module. Thanks for bringing this up.

Another idea might be to add more options to the `remoteOptions` object that's passed on to the redis wrapper and then manage the errors in there. This would mean that multi-level-cache would be responsible for recreating the instance and not the client using it.

So at its most basic you might have an `fatalErrorRecoverWait` set to, in your example 30s, and when an error is raised that matches error types that we know and that we can recover from then a `setTimeout` is called that tries to recreate the redis cache after the given time. You'd need a flag to prevent multiple setTimeouts being active at the same time.

**Comment by giles-v** [comment]
@guyellis thanks for the response. I think at this point we're going to pursue this outside of `multi-level-cache`. Here's a gist of our draft code, FWIW: https://gist.github.com/giles-v/942598b8e4e19beab035270b2cc7e791

**Comment by guyellis** [comment]
I took a quick glance - looks good @giles-v
